# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set Build Version
        run: echo "BUILD_VERSION=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Tag Release
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag "roll-masters-$BUILD_VERSION"
          git push origin "roll-masters-$BUILD_VERSION"

      - name: Retrieve History
        run: |
          git clone --branch gh-pages --single-branch https://github.com/${{ github.repository }} gh-pages
          mkdir -p dist-history
          cp -r gh-pages/v-* dist-history/

      - name: Build Roll Masters - Versioned
        run: |
          npm ci
          VITE_BUILD_VERSION=$BUILD_VERSION npm run build -- --base=roll-masters/v-$BUILD_VERSION
          mkdir -p dist-history/v-$BUILD_VERSION
          cp -r dist/* dist-history/v-$BUILD_VERSION

      - name: Build Roll Masters - Latest
        run: |
          npm ci
          VITE_BUILD_VERSION=$BUILD_VERSION npm run build -- --base=roll-masters

      - name: Copy to versioned subfolder
        run: |
          cp -r dist-history/* dist/
          rm -rf dist-history

      - name: Create Historic html page
        run: |
          mkdir -p dist/history
          cp history.html dist/history/index.html
          history_content=""
          for dir in dist/v-*; do
            history_content="$history_content<li><a href=\"/roll-masters/${dir##*/}\">${dir##*/}</a></li>"
          done
          sed -i "s|__HISTORY__|$history_content|" dist/history/index.html

      # Runs a set of commands using the runners shell
      - name: Deploy to GitHub Pages
        # You may pin to the exact commit or the version.
        # uses: JamesIves/github-pages-deploy-action@164583b9e44b4fc5910e78feb607ea7c98d3c7b9
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          # This is the branch you wish to deploy to, for example gh-pages or docs.
          branch: gh-pages
          # The folder in your repository that you want to deploy. If your build script compiles into a directory named build you would put it here. Folder paths cannot have a leading / or ./. If you wish to deploy the root directory you can place a . here.
          folder: dist
          # If you would like to push the contents of the deployment folder into a specific directory on the deployment branch you can specify it here.
          # target-folder: .
          # If you need to customize the commit message for an integration you can do so.
          commit-message: Deploy Roll Masters
